version: "3.9"
services:
  prioriza_ia:
    build:
      context: .                # contexto na raiz
      dockerfile: Dockerfile    # Dockerfile na raiz
    image: repo.adminsitracao.go.gov.br/prioriza_ia:latest
    container_name: prioriza_ia
    restart: unless-stopped
    hostname: prioriza_ia
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./app:/code/app         # monta app no mesmo caminho do Dockerfile
      - ./api:/code/api         # monta api no mesmo caminho do Dockerfile
      - ./prompts:/code/prompts # monta prompts no mesmo caminho do Dockerfile
    ports:
      - "4567:4567"
    networks:
      - netprioriza_ia
networks:
  netprioriza_ia:
    name: netprioriza_ia
    driver: bridge