version: "3.9"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    volumes:
      - ./app:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    # Adicione outras variáveis de ambiente se necessário